[package]
name = "typedb-protocol"
version = "0.0.0"
edition = "2021"

[lib]
path = "lib.rs"

[build-dependencies]
tonic-build = "^0.12"

[dependencies]
prost = "^0.13"
tonic = { version = "^0.12", features = ["tls", "tls-roots"] }
